### ISSUE TITLE
Todo issue

### ISSUE THREAD

**Issue by CDE90** [CDE90/poll-app#1]
# New features

- [x] Ability to hide a poll from the list in index
- [ ] Ability to view all polls created by user
- [ ] Ability to delete poll
- [ ] Ability to add end date/time to poll
- [ ] Possible ability to decide whether to limit votes by ip or browser/cookie (current)

# Fixes

- [ ] if `/poll/:id` doesn't exist redirect to homepage
- [ ] Fix `/poll/:id` discord link embed - isn't showing currently
- [x] Show number of votes in poll results page along with percentage
- [x] Allow poll authors to see poll results without voting themselves
